package View;

import Controller.ProjetoController;
import Modelo.*;
import Persistencia.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class ProjetoDPView extends javax.swing.JFrame {

    private CriarProjetoView criarProjetoView;
    private ProjetoController projetoController;
    

    public ProjetoDPView(ProjetoController projetoController) {      
        this.projetoController = projetoController;
        initComponents();
        for(Projeto projeto : DadosProjeto.getProjetos()){
            jComboBox1.addItem(projeto.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Criar Projeto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Criar Sprint");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Desenvolvedores");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("PÁGINA DO PROJETO");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("Criar Histórias");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(269, 269, 269))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton4))
                    .addComponent(jButton2))
                .addGap(42, 42, 42)
                .addComponent(jButton3)
                .addGap(43, 43, 43)
                .addComponent(jButton5)
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addGap(137, 137, 137))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // CRIAR PROJETO
        criarProjetoView = new CriarProjetoView(this);
        criarProjetoView.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Desenvolvedores ARRUMAR ENVIAR PARA O CONTROLE
        
        DadosUsers dadosUsers = new DadosUsers();
        ArrayList<User> desenvolvedores = DadosUsers.getUsersList();
        
        StringBuilder sb = new StringBuilder();
            for (User dev : desenvolvedores) {
            if(dev.getTipoUsuario().equals("Desenvolvedor")){
                sb.append("Nome: ").append(dev.getNome()).append("\n");
                sb.append("Tipo: ").append(dev.getTipoUsuario()).append("\n");
                sb.append("\n");
            }
        }
            
        JOptionPane.showMessageDialog(this, sb.toString(), "Funcionários", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      

        jTextArea1.setEditable(false);
        String projetoSelecionado = (String) jComboBox1.getSelectedItem();
        Projeto detalhesProjeto = projetoController.getProjetoNome(projetoSelecionado);
        
        jTextArea1.setText(exibirDetalhesProjeto(detalhesProjeto));

        pack();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // VOLTAR A VIEW
        
        DonoDoProdutoView donoDoProdutoView = new DonoDoProdutoView();
        donoDoProdutoView.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // CRIAR SPRINT
        CriarSprintView criarSprintView = new CriarSprintView();
        criarSprintView.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // CRIAR HISTORIA
        
        CriarHistoriasView criarHistoriasView = new CriarHistoriasView();
        criarHistoriasView.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    public void adicionarProjetosAoComboBox(Projeto projetos) {

        jComboBox1.addItem(projetos.getNome());

    }
    
    public String exibirDetalhesProjeto(Projeto projetos){
        StringBuilder detalhes = new StringBuilder();
        detalhes.append("ID: ").append(projetos.getId()).append("\n");
        detalhes.append("Nome: ").append(projetos.getNome()).append("\n");
        detalhes.append("Descrição: ").append(projetos.getDescricao()).append("\n");
        detalhes.append("Criado em: ").append(projetos.getCriadoEm()).append("\n");
        detalhes.append("\n");
        
        if (!projetos.getSprintLista().isEmpty()) {
            detalhes.append("Sprints do Projeto:\n");
            for (Sprint sprint : projetos.getSprintLista()) {
                detalhes.append("   - Sprint ID: ").append(sprint.getSprintId()).append("\n");
                detalhes.append("     Data de Início: ").append(sprint.getDataInicio()).append("\n");
                detalhes.append("     Data de Fim: ").append(sprint.getDataFim()).append("\n");
                detalhes.append("     Objetivo: ").append(sprint.getObjetivo()).append("\n");
            }
        } else {
            detalhes.append("Este projeto ainda não possui sprints.\n");
        }
        detalhes.append("\n");
        if (!projetos.getHistoriaLista().isEmpty()) {
            detalhes.append("Histórias do Projeto:\n");
            for (Historia historia : projetos.getHistoriaLista()) {
                detalhes.append("   - ").append(historia.getTitulo()).append(": ").append(historia.getDescricao()).append("\n");
                detalhes.append("Prioridade: ").append(historia.getPrioridade()).append("\n");
                detalhes.append("Estado: ").append(historia.getEstado()).append("\n");
            }
        } else {
            detalhes.append("Este projeto ainda não tem histórias associadas.\n");
        }
        detalhes.append("\n");
        if (!projetos.getEquipeProjeto().isEmpty()) {
            detalhes.append("Equipe do Projeto:\n");
            for (User desenvolvedor : projetos.getEquipeProjeto()) {
                detalhes.append("   - ").append(desenvolvedor.getNome()).append(": ").append(desenvolvedor.getTipoUsuario()).append("\n");
            }
        } else {
            detalhes.append("Este projeto ainda não tem uma equipe alocada.\n");
        }

        return detalhes.toString();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
